package me.buzz.woolwars.game;

public class TODO {

    //TODO: FARE IL REJOIN TRAMITE UNA CACHE DI 3 MINUTI NELLA QUALE VI E' IL NOME DEL PLAYER E L'ID DELL ULTIMO GAME NEL QUALE E' ENTRATO

    /*

    FARE NUOVO STATO:

    WAITING (IN ATTESA DI GIOCATORI)
    STARTING (COOLDOWN PER TP)
    PRE-PLAYING (SELEZIONE CLASSI)
    PLAYING (GIOCANDO)
    ENDED (FINE)


     */

}
